"""CI pipeline scaffolding.

``polygraph scaffold-ci <provider>`` writes a working starter pipeline that runs
the harness as a gate: validate the config, run + score with the regression gate,
emit JUnit + SARIF artifacts (so results land in the CI's test + security tabs),
post PR feedback, and run an authorized red-team pass. The generated files are
ready to commit; edit the config path and drop ``--mock`` once an adapter points
at a real system.
"""

from __future__ import annotations

from pathlib import Path

_GITHUB = """\
# Generated by `polygraph scaffold-ci github`. Runs PromptPolygraph as a CI gate.
name: promptpolygraph
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write   # for the PR-comment step
  checks: write          # for annotations

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install promptpolygraph
      # Fail fast on a malformed config before spending any tokens.
      - run: polygraph validate-config --config {config}
      # Run + score with the regression gate. Drop --mock and set ANTHROPIC_API_KEY
      # (or a local provider) once the adapter points at a real system.
      - name: Evaluate
        run: |
          polygraph all --config {config} --mock --format md,html
          RUN=$(ls -t polygraph_out | head -1)
          echo "RUN=$RUN" >> "$GITHUB_ENV"
      - name: Gate + PR feedback
        run: |
          polygraph analyze --config {config} --mock --run "$RUN" --ci \\
            --baseline rolling:5 --github-annotations --pr-comment pr.md
      - name: Machine-readable reports (JUnit + SARIF)
        if: always()
        run: polygraph report --config {config} --run "$RUN" --format junit,sarif
      - name: Upload SARIF to code scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: polygraph_out/${{{{ env.RUN }}}}/report.sarif.json
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: polygraph-reports
          path: polygraph_out/${{{{ env.RUN }}}}/

  redteam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install promptpolygraph
      - name: Authorized red-team
        run: polygraph redteam --config {config} --mock --format md,sarif,junit
      - name: Upload red-team SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: polygraph_out
"""

_GITLAB = """\
# Generated by `polygraph scaffold-ci gitlab`.
stages: [test]

promptpolygraph:
  stage: test
  image: python:3.12-slim
  script:
    - pip install promptpolygraph
    - polygraph validate-config --config {config}
    - polygraph all --config {config} --mock --format md,html
    - RUN=$(ls -t polygraph_out | head -1)
    - polygraph analyze --config {config} --mock --run "$RUN" --ci --baseline rolling:5
    - polygraph report --config {config} --run "$RUN" --format junit,sarif
  artifacts:
    when: always
    paths:
      - polygraph_out/
    reports:
      junit: polygraph_out/*/report.junit.xml
"""

_JENKINS = """\
// Generated by `polygraph scaffold-ci jenkins`.
pipeline {{
  agent {{ docker {{ image 'python:3.12' }} }}
  stages {{
    stage('PromptPolygraph') {{
      steps {{
        sh 'pip install promptpolygraph'
        sh 'polygraph validate-config --config {config}'
        sh 'polygraph all --config {config} --mock --format md,html'
        sh '''
          RUN=$(ls -t polygraph_out | head -1)
          polygraph analyze --config {config} --mock --run "$RUN" --ci --baseline rolling:5
          polygraph report --config {config} --run "$RUN" --format junit,sarif
        '''
      }}
    }}
  }}
  post {{
    always {{
      junit testResults: 'polygraph_out/*/report.junit.xml', allowEmptyResults: true
      archiveArtifacts artifacts: 'polygraph_out/**', allowEmptyArchive: true
    }}
  }}
}}
"""

_PRECOMMIT = """\
# Generated by `polygraph scaffold-ci precommit`. Install: pre-commit install
repos:
  - repo: local
    hooks:
      - id: polygraph-validate-config
        name: polygraph validate-config
        entry: polygraph validate-config --config {config}
        language: system
        files: '{config}$'
        pass_filenames: false
"""

_PROVIDERS = {
    "github": (".github/workflows/promptpolygraph.yml", _GITHUB),
    "gitlab": (".gitlab-ci.yml", _GITLAB),
    "jenkins": ("Jenkinsfile", _JENKINS),
    "precommit": (".pre-commit-config.yaml", _PRECOMMIT),
}


def providers() -> list[str]:
    return list(_PROVIDERS)


def scaffold_ci(provider: str, *, config: str = "config.yaml",
                root: str | Path = ".", force: bool = False) -> dict:
    """Write the starter file for `provider`. Returns {path, written, skipped}."""
    if provider not in _PROVIDERS:
        raise ValueError(f"unknown provider '{provider}'; choose from {', '.join(_PROVIDERS)}")
    rel, template = _PROVIDERS[provider]
    dest = Path(root) / rel
    if dest.exists() and not force:
        return {"path": str(dest), "written": False, "skipped": True}
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(template.format(config=config))
    return {"path": str(dest), "written": True, "skipped": False}
